# Generated by Django 2.2.4 on 2019-09-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(choices=[('Andersonville', 'Andersonville'), ('Archer Heights', 'Archer Heights'), ('Ashburn', 'Ashburn'), ('Ashburn Estates', 'Ashburn Estates'), ('Austin', 'Austin'), ('Avaondale', 'Avaondale'), ('Belmont Central', 'Belmont Central'), ('Beverly', 'Beverly'), ('Beverly Woods', 'Beverly Woods'), ('Brainerd', 'Beverly Woods'), ('Bridgeport', 'Bridgeport'), ('Brighton Park', 'Brighton Park'), ('Bronceville', 'Bronceville'), ('Bucktown', 'Bucktown'), ('Burnside', 'Burnside'), ('Calumet Heights', 'Calumet Heights'), ('Canaryville', 'Canaryville'), ('Clearing', 'Clearing'), ('Chatham', 'Chatham'), ('Chinatown', 'Chinatown'), ('Cottage Grove Heights', 'Cottage Grove Heights'), ('Cragin', 'Cragin'), ('Dunning', 'Dunning'), ('East Chicago', 'East Chicago'), ('Edison Park', 'Edison Park'), ('Edgebrook', 'Edgebrook'), ('Edgewater', 'Edgewater'), ('Englewood', 'Englewood'), ('Ford City', 'Ford City'), ('Gage Park', 'Gage Park'), ('Galewood', 'Galewood'), ('Garfield Park', 'Garfield Park'), ('Garfield Ridge', 'Garfield Ridge'), ('Gold Coast', 'Gold Coast'), ('Grand Crossing', 'Grand Crossing'), ('Gresham', 'Gresham'), ('Hamilton Park', 'Hamilton Park'), ('Humboldt Park', 'Humboldt Park'), ('Hyde Park', 'Hyde Park'), ('Jefferson Park', 'Jefferson Park'), ('Kelvyn Park', 'Kelvyn Park'), ('Kenwood', 'Kenwood'), ('Kilbourn Park', 'Kilbourn Park'), ('Lake Meadows', 'Lake Meadows'), ('Lakeview', 'Lakeview'), ('Lawndale', 'Lawndale'), ('Lincoln Park', 'Lincoln Park'), ('Lincoln Square', 'Lincoln Square'), ('Little Village', 'Little Village'), ('Logan Square', 'Logan Square'), ('Longwood Manor', 'Longwood Manor'), ('Loop', 'Loop'), ('Marquette Park', 'Marquette Park'), ('McKinley Park', 'McKinley Park'), ('Midway', 'Midway'), ('Morgan Park', 'Morgan Park'), ('Montclare', 'Montclare'), ('Mount Greenwood', 'Mount Greenwood'), ('North Center', 'North Center'), ('Norwood Park', 'Norwood Park'), ('Old Irving Park', 'Old Irving Park'), ('Old Town', 'Old Town'), ('Park Manor', 'Park Manor'), ('Pilsen', 'Pilsen'), ('Princeton Park', 'Princeton Park'), ('Portage Park', 'Portage Park'), ('Pullman', 'Pullman'), ('Ravenswood', 'Ravenswood'), ('River North', 'River North'), ('River West', 'River West'), ('Rodgers Park', 'Rodgers Park'), ('Roscoe VIllage', 'Roscoe VIllage'), ('Roseland', 'Roseland'), ('Sauganash', 'Sauganash'), ('Schorsch Village', 'Schorsch Village'), ('Scottsdale', 'Scottsdale'), ('South Chicago', 'South Chicago'), ('South Deering', 'South Deering'), ('South Loop', 'South Loop'), ('South Shore', 'South Shore'), ('Streeterville', 'Streeterville'), ('Tri-Taylor', 'Tri-Taylor'), ('Ukrainian Village', 'Ukrainian Village'), ('United Center', 'United Center'), ('Uptown', 'Uptown'), ('Vittum Park', 'Vittum Park'), ('Washington Heights', 'Washington Heights'), ('West Elsdon', 'West Elsdon'), ('West Loop', 'West Loop'), ('West Pullman', 'West Pullman'), ('Westlawn', 'Westlawn'), ('Wicker Park', 'Wicker Park'), ('Woodlawn', 'Woodlawn'), ('Wrigleyville', 'Wrigleyville'), ('Wrigtwood', 'Wrigtwood')], max_length=200),
        ),
    ]
