# Generated by Django 2.2.4 on 2019-09-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190924_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(default='Chicago', max_length=100),
        ),
    ]
