# Generated by Django 2.2.4 on 2019-09-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190924_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(default='IL', max_length=100),
        ),
    ]
