# Generated by Django 2.2.4 on 2019-09-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='job_title',
            field=models.CharField(default='Realtor', max_length=200),
        ),
    ]
